### ISSUE TITLE
Why not improving the example with front end login with angularJS?

### ISSUE THREAD

**Issue by mappedinn** [chalasr/lexik-jwt-authentication-sandbox#1]
Hi,

This is a nice example! Working perfectly :+1:  :+1: 

As an improvement, Why not improving the example with front end login with angularJS?

**Comment by chalasr** [comment]
@mappedinn Glad to hear that. Note that this has a `2.x` branch which is adapted to the `2.0` version of `LexikJWTAuthenticationBundle` (which should be released in the next week), you can use it as an example of upgrade path (even if it is clearly explained in the bundle itself).

About adding a front-end login, why not! if you or someone else can pick this issue it would be awesome, otherwise I'll do it as soon as possible.

Thank you for opening this issue!
